name: ci
on:
  push:
    branches:
      - master
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - run: pip install mkdocs-material==8.1.4
      - run: pip install mkdocs==1.2.4
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
